### ISSUE TITLE
[BUG]: Journal error

### ISSUE THREAD

**Issue by dfurray** [HizurosWoWAddOns/FollowerLocationInfo#1]
### WoW client

WoW Retail

### What happened?

1x ...face/AddOns/FollowerLocationInfo_Journal/Journal.lua:1592: SetPortraitToTexture(): Couldn't find texture named '(null)'
[string "=[C]"]: in function `SetPortraitToTexture'
[string "@Interface/AddOns/FollowerLocationInfo_Journal/Journal.lua"]:1592: in function <...face/AddOns/FollowerLocationInfo_Journal/Journal.lua:1574>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/FollowerLocationInfo/Core.lua"]:637: in function <Interface/AddOns/FollowerLocationInfo/Core.lua:540>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:704: in function `CollectionsJournal_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1152: in function `SetCollectionsJournalShown'
[string "@Interface/FrameXML/UIParent.lua"]:1146: in function `ToggleCollectionsJournal'
[string "TOGGLECOLLECTIONS"]:1: in function <[string "TOGGLECOLLECTIONS"]:1>

Locals:
(*temporary) = nil
(*temporary) = "Icons\Achievement_GarrisonFollower_Rare"

**Comment by nancikennedy** [comment]
Adding this, as I was testing with just FLI installed and it has a bit different info about the same error...

Message: ...face/AddOns/FollowerLocationInfo_Journal/Journal.lua:1592: SetPortraitToTexture(): Couldn't find texture named '(null)'
Time: Sat Oct 29 23:47:31 2022
Count: 1
Stack: ...face/AddOns/FollowerLocationInfo_Journal/Journal.lua:1592: SetPortraitToTexture(): Couldn't find texture named '(null)'
[string "=[C]"]: in function `SetPortraitToTexture'
[string "@Interface/AddOns/FollowerLocationInfo_Journal/Journal.lua"]:1592: in function <...face/AddOns/FollowerLocationInfo_Journal/Journal.lua:1574>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/FollowerLocationInfo/Core.lua"]:637: in function <Interface/AddOns/FollowerLocationInfo/Core.lua:540>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:704: in function `CollectionsJournal_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1152: in function `SetCollectionsJournalShown'
[string "@Interface/FrameXML/UIParent.lua"]:1146: in function `ToggleCollectionsJournal'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:968: in function <Interface/FrameXML/MainMenuBarMicroButtons.lua:966>
[string "=[C]"]: ?

Locals: (*temporary) = nil
(*temporary) = "Interface\Icons\Achievement_GarrisonFollower_Rare"

**Comment by hizuro** [comment]
Thank you for reporting.
Next update will be disable the docked mode on collections.

The code is outcommented. i've fixed the errors but miss the tab button under Collections. Need more time.

Update coming soon.

Greetings Hizuro
