### ISSUE TITLE
[BUG]: BROKE AF!!!

### ISSUE THREAD

**Issue by Neipas09** [HizurosWoWAddOns/FollowerLocationInfo#4]
### WoW client

WoW Retail

### What happened?

1. Minimap button opens "Collections" window.
2. Reset command gets rid of minimap button, and unable to bring it back with [/fli minimap] command
3. Command [/fli journal] shows "Collections" window.

**Comment by hizuro** [comment]
Thank you for reporting.
Both modes should work again.
